#!/usr/bin/env python
from tango.server import server_run
from tango_simlib.tango_sim_generator import (configure_device_model, get_tango_device_server)


# File generated on Fri Apr 13 17:20:59 2018 by tango-simlib-generator


def main():
    sim_data_files = ['/home/kat/svn/tango-simlib/tango_simlib/tests/config_files/databaseTest.fgo']
    model = configure_device_model(sim_data_files)
    TangoDeviceServers = get_tango_device_server(model, sim_data_files)
    server_run(TangoDeviceServers)

if __name__ == "__main__":
    main()
