#!/usr/bin/env python
from PyTango.server import server_run
from tango_simlib.tango_sim_generator import (configure_device_model, get_tango_device_server)


# File generated on Thu Jul 20 09:33:11 2017 by tango-simlib-generator


def main():
    sim_data_files = ['/home/kat/svn/tango-simlib/tango_simlib/tests/Weather.xmi', '/home/kat/svn/tango-simlib/tango_simlib/tests/Weather_SIMDD.json']
    model = configure_device_model(sim_data_files)
    TangoDeviceServers = get_tango_device_server(model, sim_data_files)
    server_run(TangoDeviceServers)

if __name__ == "__main__":
    main()
