name: Unit Tests
on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: nexus.engageska-portugal.pt/ska-docker/ska-python-buildenv:9.3.3.1
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo pip3 install nose nose_xunitmp
      - name: Install test requirements
        run: |
          sudo pip3 install katcp mock numpy
      - name: Install and run tests for Python 3.7
        run: |
          sudo python3 -m pip install -U . && \
          sudo python3 -m nose --with-xunitmp
