name: Unit Tests
on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: nexus.engageska-portugal.pt/ska-docker/tango-pytango:9.3.3.1
    steps:
      - name: test
        run: echo 'Welcome to Github Actions'
      - name: Install git
        run: |
          sudo apt-get update -y && \
          apt install git
      - uses: actions/checkout@v2   # Checks out the code
      - name: Check mysql service
        run: service mysql start && service mysql status || exit 1
      - name: Check tango-db service
        run: service tango-db start && service tango-db status || exit 1
      - name: Install dependencies
        run: |
          apt install -y python-pip python3-pip && \
          pip install --upgrade pip && \
          pip3 install --upgrade pip && \
          pip install --upgrade setuptools && \
          pip3 install --upgrade setuptools && \
          pip install nose && \
          pip3 install nose && \
          pip install nose_xunitmp && \
          pip3 install nose_xunitmp
      - name: Install and run tests for Python 2.7
        run: |
          python2 -m pip install -U . && \
          python2 -m nose --with-xunitmp
