name: Unit Tests
on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: nexus.engageska-portugal.pt/ska-docker/tango-example:0.3.1
    steps:
      - name: test
        run: echo 'Welcome to Github Actions'
      - name: Install git
        run: |
          sudo apt-get update -y && \
          sudo apt install git -y
      - uses: actions/checkout@v1   # Checks out the code
      # - name: Check mysql service
      #   run: service mysql start && service mysql status || exit 1
      # - name: Check tango-db service
      #   run: service tango-db start && service tango-db status || exit 1
      - name: Install dependencies
        run: |
          sudo pip install nose && \
          sudo pip3 install nose && \
          sudo pip install nose_xunitmp && \
          sudo pip3 install nose_xunitmp
      - name: Install and run tests for Python 2.7
        run: |
          python -m pip install -U . && \
          python -m nose --with-xunitmp
