name: Unit Tests
on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: kmadisa47/tango_db:9.3.0
    steps:
      - name: test
        run: echo 'Welcome to Github Actions'
      - uses: actions/checkout@v2   # Checks out the code
      - name: Check mysql service
        run: service mysql start && service mysql status || exit 1
      - name: Check tango-db service
        run: service tango-db start && service tango-db status || exit 1
